"""Git-backed projects with a server working copy.

The roaming requirement, restated as a data problem: your design markdown and the
board it generates must live somewhere that follows you between workstations, not
on whichever laptop you happen to be at. So they live on the server, in a working
copy under one projects root, and that working copy is backed by a git remote.
You edit markdown locally and push; the server pulls. Or you edit on the server
(via the app) and it commits and pushes. Either way, git is the sync spine and
the server is the always-on copy.

This module is a thin, auditable wrapper over the ``git`` CLI — not a
reimplementation of git, and not GitPython. Every method shells out to git with a
fixed argv (never a shell string), scoped to one project directory that is proven
to sit under the projects root before anything runs. Remotes and branches come
from blpl.toml, not from the request, so a caller cannot point the server at an
arbitrary URL.

Authentication to the remote is deliberately not handled here. On the deploy, git
uses whatever the environment gives it — an SSH deploy key mounted into the
container, or a credential helper. Keeping auth out of this file means no token
ever passes through application code or lands in a log line.
"""

from __future__ import annotations

import os
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import urlsplit


class ProjectError(RuntimeError):
    """A git or filesystem operation on a project failed. Carries the git stderr
    so the UI can show what actually went wrong instead of a generic 500."""


# Paths that are always changing and are never work anyone would lose: the
# conversation log grows on every turn, the usage ledger on every call, and
# .pipeline/ is regenerated by the next run. They are still committed — see
# commit_all — but they must not drive the "uncommitted" badge.
#
# They did, and that made the badge useless. It was lit permanently, because
# having a conversation dirties the tree, so it said "you have talked to the
# assistant" while appearing to say "you have unsaved design work". A warning
# that is always on is not a warning, and this one was sitting next to the
# question of whether anything was being version-controlled at all.
_BOOKKEEPING = (".blpl/", ".pipeline/")

# What a project does not carry in its history, and why each line is here.
#
# The test is not "is this file useful" — it is "would losing this cost
# anything that cannot be had back". A 53 MB .git on a project of half a dozen
# markdown files is a real cost, paid on every clone, worktree and backup, and
# most of it was output.
#
# Deliberately absent: datasheets/ (evidence for a decision, and a vendor may
# withdraw a PDF), datasheets/extracted/ (regenerable only by spending money
# again), .blpl/ (the conversation log holds the full text of every proposal —
# it churns, which is why it does not light the badge, but it is worth
# keeping), and context-ignore/, which is about attention rather than storage
# and whose whole point is that the files stay in the project.
BASELINE_GITIGNORE = """\
# Pipeline output. Every file here is regenerated by re-running the stage that
# made it, including the compiled KiCad project — the design documents are the
# source, and this is the build directory.
.pipeline/

# Quarantine. Files fetched from the network live here until they have been
# inspected and scanned, and are moved into the project when they pass. Putting
# an uncleared download into permanent history is the one place it should never
# end up. The ledger stays: it is the provenance record.
retrieved/*
!retrieved/quarantine.json

# KiCad's local scratch: window state, autosaves, backups, caches. Per-machine
# and per-person, never part of the design.
*.kicad_prl
*-backups/
fp-info-cache
*.kicad_sch-bak
*.kicad_pcb-bak

# macOS artifacts. These arrive here the way they arrive everywhere: inside a
# vendor's zip. Nothing reads them on any operating system, macOS included —
# __MACOSX is a resource fork for a filesystem that stopped needing one in
# Mac OS 9, and .DS_Store is a folder's window position.
.DS_Store
._*
__MACOSX/
.AppleDouble
.Spotlight-V100
.Trashes
.fseventsd
"""


@dataclass(frozen=True)
class GitStatus:
    branch: str
    ahead: int          # local commits not yet pushed
    behind: int         # remote commits not yet pulled
    dirty: bool         # uncommitted changes to design files
    has_remote: bool
    #: The remote's name and where it points. Reported because "has_remote:
    #: true" answers a question nobody asks — the branch label was visible in
    #: the UI while *which repository it pushed to* appeared nowhere at all,
    #: which is a poor property for a control that pushes.
    remote_name: str = ""
    remote_url: str = ""


def _redact_url(url: str) -> str:
    """A remote URL with any embedded credentials removed.

    ``gitstore`` is careful never to splice a token into a URL, but this one is
    not ours: it is whatever the user pasted into the clone form, and
    ``https://user:ghp_xxx@github.com/...`` is a shape people paste. Displaying
    it would put a live token on screen, in a screenshot, and in any bug report
    made from one. The userinfo is replaced rather than dropped so the URL still
    reads as authenticated, which is information worth keeping.
    """
    match = re.match(r"^([a-zA-Z][a-zA-Z0-9+.-]*://)([^/@]+)@(.*)$", url)
    if not match:
        return url
    scheme, userinfo, rest = match.groups()
    user = userinfo.split(":", 1)[0]
    return f"{scheme}{user}:***@{rest}" if ":" in userinfo else f"{scheme}{user}@{rest}"


# Remote transports git may use for anything a user names. Read by both the URL
# check below and git itself (GIT_ALLOW_PROTOCOL), so the two cannot disagree.
# `file` is for the test suite's local bare repositories and nothing else: a
# deployment that allowed it would let any signed-in user clone another
# project's repository off the server's own disk into a project they own.
_DEFAULT_PROTOCOLS = "https:ssh"


def allowed_protocols() -> list[str]:
    raw = os.environ.get("BLPL_GIT_ALLOWED_PROTOCOLS", _DEFAULT_PROTOCOLS)
    return [p.strip().lower() for p in raw.split(":") if p.strip()]


def _net_env(env: dict[str, str] | None) -> dict[str, str]:
    """Environment for a git command that talks to a remote."""
    return {**(env or {}), "GIT_ALLOW_PROTOCOL": ":".join(allowed_protocols())}


_SCP_LIKE = re.compile(r"^(?P<user>[A-Za-z0-9._-]+)@(?P<host>[A-Za-z0-9.-]+):(?P<path>[^:].*)$")


def check_remote_url(url: str) -> str:
    """The remote URL, if it is one a user may point a project at. Else raise.

    Accepted: https://host/..., ssh://host/..., and git's user@host:path. Not:
    local paths and file:// (another repository on this server's disk — the
    clone route copied them for any signed-in user), transport helpers such as
    ext::, and anything git could read as an option. `file` is accepted only
    when BLPL_GIT_ALLOWED_PROTOCOLS includes it, which the test suite does.
    """
    raw = (url or "").strip()
    if not raw:
        raise ProjectError("a remote URL is required")
    if raw.startswith("-") or any(c.isspace() or ord(c) < 32 for c in raw):
        raise ProjectError(f"{raw[:60]!r} is not a remote URL")
    allowed = allowed_protocols()
    if "://" in raw:
        scheme = raw.split("://", 1)[0].lower()
        if scheme not in allowed:
            raise ProjectError(
                f"{scheme}:// remotes are not allowed here; use an https:// or ssh:// URL"
            )
        if scheme != "file" and not urlsplit(raw).hostname:
            raise ProjectError(f"{raw[:60]!r} names no host")
        return raw
    if "::" in raw:
        raise ProjectError("git transport helpers (such as ext::) are not allowed")
    m = _SCP_LIKE.match(raw)
    if m and "ssh" in allowed:
        return raw
    if raw.startswith("/") and "file" in allowed:
        return raw
    raise ProjectError(
        f"{raw[:60]!r} is not a remote URL — use https://host/owner/repo.git "
        "or git@host:owner/repo.git (local paths are not allowed)"
    )


class Projects:
    def __init__(self, root: Path):
        self.root = Path(root).resolve()
        self.root.mkdir(parents=True, exist_ok=True)

    def project_dir(self, name: str) -> Path:
        """Resolve a project name to a directory under the root, refusing escape.

        The name reaches here from a URL, a form field, or config, so ``../`` is
        on the table. A project is one directory directly under the root — a
        separator in the name would create (or address) a nested directory that
        every listing then misses, so multi-component names are refused outright.
        Resolve, then prove the result is still inside the root — the same guard
        the file endpoints use, kept in one place.
        """
        if not name or name.startswith(".") or "/" in name or "\\" in name:
            raise ProjectError(f"invalid project name {name!r}")
        candidate = (self.root / name).resolve()
        if candidate != self.root and self.root not in candidate.parents:
            raise ProjectError(f"invalid project name {name!r}")
        return candidate

    def exists(self, name: str) -> bool:
        return self.project_dir(name).is_dir()

    # -- lifecycle -----------------------------------------------------------

    def clone(
        self, name: str, remote: str, branch: str = "main",
        *, env: dict[str, str] | None = None,
    ) -> Path:
        """Clone a remote into a new working copy. Fails if the dir already exists,
        rather than clobbering whatever is there.

        The baseline ignore rules are deliberately *not* applied here. A cloned
        project already has a history and possibly its own rules, and untracking
        files in it would be a change to a shared repository made on somebody
        else's behalf — pushed the next time anyone pushes. Run
        ``apply_baseline_gitignore`` explicitly if that is what is wanted.
        """
        dest = self.project_dir(name)
        if dest.exists():
            raise ProjectError(f"project {name!r} already exists at {dest}")
        remote = check_remote_url(remote)
        if branch.startswith("-"):
            raise ProjectError(f"{branch!r} is not a branch name")
        # `--` so nothing user-supplied can be read as an option to clone.
        self._git(
            self.root, "clone", "--branch", branch, "--", remote, dest.name, env=_net_env(env)
        )
        self._ensure_identity(dest)
        return dest

    def init_local(self, name: str) -> Path:
        """Create a fresh git repo for a project that has no remote yet.

        A new design starts as a local working copy; a remote can be attached
        later by adding it to blpl.toml and pushing. `git init` here means even a
        local-only project has a history from its first commit.
        """
        dest = self.project_dir(name)
        if dest.exists():
            raise ProjectError(f"project {name!r} already exists at {dest}")
        dest.mkdir(parents=True)
        self._git(dest, "init", "-b", "main")
        self._ensure_identity(dest)
        # An empty initial commit, so HEAD exists from the start. `git init`
        # alone leaves an unborn HEAD, which reads as a repository right up until
        # something asks it for a commit — and a worktree cannot be branched from
        # a HEAD that points at nothing, so sharing a brand-new project failed
        # with a git error nobody would connect to "it has never been committed".
        # The docstring above always claimed this; now it is true.
        self._git(dest, "commit", "--allow-empty", "-m", "Create project")
        self.apply_baseline_gitignore(name)
        return dest

    def apply_baseline_gitignore(self, name: str) -> list[str]:
        """Install the baseline ignore rules, and untrack anything they now cover.

        Idempotent, and safe to run on a project that already has history. The
        second half is the part that matters on an existing repository: adding
        the file changes nothing on its own, because git keeps tracking what it
        already tracks. Returns the paths that were untracked, so a caller can
        say what happened rather than claiming a cleanup it did not do.

        Untracking removes a path from the index, never from the working tree:
        the artifacts stay exactly where they are and the next run overwrites
        them as usual. Past commits keep their copies — this stops the history
        growing, it does not rewrite it.
        """
        d = self._require(name)
        f = d / ".gitignore"
        changed = False
        if not f.exists():
            f.write_text(BASELINE_GITIGNORE, encoding="utf-8")
            changed = True
        elif "\n.pipeline/\n" not in "\n" + f.read_text(encoding="utf-8"):
            # A project with its own .gitignore keeps it; the baseline is
            # appended rather than imposed, because someone who wrote rules for
            # their board had a reason.
            with f.open("a", encoding="utf-8") as fh:
                fh.write("\n" + BASELINE_GITIGNORE)
            changed = True

        listed = self._git_allow_fail(d, "ls-files", "--cached", "--ignored", "--exclude-standard")
        untracked = [line for line in listed.splitlines() if line.strip()]
        if untracked:
            # -r for directories, --cached so nothing leaves the disk. Batched
            # because a project can have hundreds of artifacts and argv is not
            # unlimited.
            for i in range(0, len(untracked), 200):
                self._git(d, "rm", "-r", "--cached", "--quiet", "--", *untracked[i : i + 200])
        if changed or untracked:
            self._git(d, "add", "-A")
            if self._is_dirty(d):
                self._git(
                    d,
                    "commit",
                    "-m",
                    "Stop tracking generated and quarantined files"
                    if untracked
                    else "Add baseline .gitignore",
                )
        return untracked

    # -- sync ----------------------------------------------------------------

    def set_remote(self, checkout: Path, url: str, *, remote: str = "origin") -> str:
        """Point a project at a remote, adding it or changing its URL.

        Set in the repository's config, so every member's worktree — which
        shares that config — sees the same remote.
        """
        url = check_remote_url(url)
        d = self._checkout("", checkout)
        if remote in self._git(d, "remote").split():
            self._git(d, "remote", "set-url", remote, url)
        else:
            self._git(d, "remote", "add", remote, url)
        return url

    def remote_of(self, name: str) -> str:
        """The origin URL, or "" for a local-only project. For credential
        matching — which is why a missing remote is an empty answer, not an
        error: no remote means no credential could apply."""
        return self._git_allow_fail(self.project_dir(name), "remote", "get-url", "origin")

    def pull(
        self, name: str, *, env: dict[str, str] | None = None, checkout: Path | None = None
    ) -> str:
        """Fast-forward the working copy from its remote. Returns git's output.

        Deliberately not a merge or rebase of divergent history: if the server
        copy has diverged, that is a conflict a human resolves, not something the
        app papers over. --ff-only turns divergence into a clear error.
        """
        d = self._checkout(name, checkout)
        if self._has_remote(d) and not self._upstream(d):
            branch = self._git(d, "branch", "--show-current").strip()
            raise ProjectError(
                f"branch {branch!r} has no upstream to pull from yet; push it first"
            )
        return self._git(d, "pull", "--ff-only", env=_net_env(env))

    def commit_all(self, name: str, message: str) -> str | None:
        """Stage everything and commit. Returns the commit output, or None if the
        tree was clean (nothing to commit is not an error)."""
        return self._commit(self._require(name), message)

    def _checkout(self, name: str, checkout: Path | None) -> Path:
        """The directory a git operation runs in: the caller's own checkout when
        given (a member's worktree), else the repository directory itself.

        Every operation a member triggers has to run in the same checkout. The
        first version of this fix moved commit and left push behind, so "Commit
        + Push" committed the member's worktree and then pushed the owner's
        unchanged branch, and reported success.
        """
        if checkout is None:
            return self._require(name)
        d = Path(checkout)
        if not (d / ".git").exists():
            raise ProjectError(f"{d.name!r} is not a git checkout")
        return d

    def _has_remote(self, d: Path) -> bool:
        return bool(self._git(d, "remote").strip())

    def _upstream(self, d: Path) -> str:
        return self._git_allow_fail(
            d, "rev-parse", "--abbrev-ref", "--symbolic-full-name", "@{upstream}"
        ).strip()

    def commit_checkout(self, checkout: Path, message: str) -> str | None:
        """``commit_all`` for a checkout the caller already resolved.

        A member's edits land in their own worktree, not in the repository
        directory ``commit_all`` names, so a route that wrote through
        ``_project_dir`` has to commit in the directory it wrote to. Committing
        by project name instead left the member's file uncommitted and swept
        whatever the owner had uncommitted into a commit named after somebody
        else's edit.

        A worktree's ``.git`` is a file pointing back at the repository, not a
        directory, which is why this cannot go through ``_require``.
        """
        return self._commit(self._checkout("", checkout), message)

    def _commit(self, d: Path, message: str) -> str | None:
        self._git(d, "add", "-A")
        if not self._is_dirty(d):
            return None
        return self._git(d, "commit", "-m", message)

    def push(
        self, name: str, *, env: dict[str, str] | None = None, checkout: Path | None = None
    ) -> str:
        d = self._checkout(name, checkout)
        if self._has_remote(d) and not self._upstream(d):
            # A member's worktree branch starts with no upstream, and a plain
            # push then refuses. Publish it under its own name, and track it so
            # status can count ahead and behind from then on.
            names = self._git(d, "remote").split()
            remote = "origin" if "origin" in names else names[0]
            return self._git(d, "push", "--set-upstream", remote, "HEAD", env=_net_env(env))
        return self._git(d, "push", env=_net_env(env))

    # -- inspection ----------------------------------------------------------

    def status(self, name: str, *, checkout: Path | None = None) -> GitStatus:
        d = self._checkout(name, checkout)
        # --show-current works before the first commit (an "unborn" branch), where
        # rev-parse HEAD would fail. A just-initialized local project has a branch
        # name but no commit yet, and that is a valid state to report on.
        branch = self._git(d, "branch", "--show-current").strip()
        dirty = self._has_design_changes(d)
        has_remote = bool(self._git(d, "remote").strip())
        ahead = behind = 0
        if has_remote:
            # Counts against the upstream, when one is configured. No upstream
            # (a fresh local repo) leaves both at zero, which is the truth.
            counts = self._git_allow_fail(
                d, "rev-list", "--left-right", "--count", "@{upstream}...HEAD"
            )
            if counts:
                parts = counts.split()
                if len(parts) == 2:
                    behind, ahead = int(parts[0]), int(parts[1])
        remote_name = ""
        remote_url = ""
        if has_remote:
            # "origin" when it exists, else whatever the first remote is called:
            # a clone names it origin, but a repository someone set up by hand
            # need not have one, and reporting nothing in that case would be the
            # same blind spot in a different place.
            names = self._git(d, "remote").split()
            remote_name = "origin" if "origin" in names else names[0]
            remote_url = _redact_url(
                self._git_allow_fail(d, "remote", "get-url", remote_name).strip()
            )
        return GitStatus(branch=branch, ahead=ahead, behind=behind, dirty=dirty,
                         has_remote=has_remote, remote_name=remote_name, remote_url=remote_url)

    # -- diff ----------------------------------------------------------------

    def diff(
        self,
        name: str,
        *,
        max_file_bytes: int = 60_000,
        max_total_bytes: int = 500_000,
        checkout: Path | None = None,
    ) -> dict:
        """What has changed in the working copy since the last commit.

        This is the "what did that run actually do" view: after a pipeline run, the
        generated artifacts and any edited markdown show up here as the delta from
        HEAD. It respects .gitignore (a project that doesn't track .pipeline/ simply
        won't see those files, which is that project's stated intent) and includes
        untracked files as additions.

        Diffs are capped: a regenerated .kicad_pcb can be enormous, and nobody
        reads a 2MB unified diff. Per-file output over the cap, and everything once
        the running total is blown, comes back with ``diff: null`` and a truncated
        flag — the file still appears with its +/- counts, just not its body.
        """
        d = self._checkout(name, checkout)
        has_head = bool(self._git_allow_fail(d, "rev-parse", "--verify", "HEAD"))
        porcelain = self._git(d, "status", "--porcelain=v1", "-uall")

        files: list[dict] = []
        total = 0
        for line in porcelain.splitlines():
            if len(line) < 4:
                continue
            xy, path = line[:2], line[3:]
            if " -> " in path:  # rename: report the destination
                path = path.split(" -> ", 1)[1]
            path = path.strip().strip('"')
            untracked = xy == "??"

            if untracked:
                # --no-index against /dev/null renders a new file as an addition.
                # It exits 1 (there is a difference), so capture regardless.
                raw = self._git_capture(d, "diff", "--no-index", "--", "/dev/null", path)
            elif has_head:
                raw = self._git_capture(d, "diff", "HEAD", "--", path)
            else:
                raw = self._git_capture(d, "diff", "--cached", "--", path) or self._git_capture(
                    d, "diff", "--", path
                )

            additions = sum(1 for ln in raw.splitlines() if ln.startswith("+") and not ln.startswith("+++"))
            deletions = sum(1 for ln in raw.splitlines() if ln.startswith("-") and not ln.startswith("---"))

            too_big = len(raw.encode("utf-8", "replace")) > max_file_bytes
            binary = "\x00" in raw or "Binary files" in raw
            if too_big or binary or total >= max_total_bytes:
                diff_text = None
            else:
                diff_text = raw
                total += len(raw)

            files.append(
                {
                    "path": path,
                    "status": _porcelain_status(xy),
                    "additions": additions,
                    "deletions": deletions,
                    "diff": diff_text,
                    "truncated": diff_text is None,
                    "binary": binary,
                }
            )

        files.sort(key=lambda f: f["path"])
        return {"clean": not files, "files": files}

    # -- internals -----------------------------------------------------------

    def _ensure_identity(self, project_dir: Path) -> None:
        """Give the repo a committer identity if the environment has none.

        ``git commit`` refuses to run without user.name/user.email, and the
        deploy container has no global git config — so every server-side commit
        would fail on a clean install. Set a repo-local identity only when
        nothing resolves; a real configured identity (global or system) wins.
        """
        if not self._git_allow_fail(project_dir, "config", "user.email"):
            self._git(project_dir, "config", "user.email", "blpl@localhost")
            self._git(project_dir, "config", "user.name", "BLPL")

    def _require(self, name: str) -> Path:
        d = self.project_dir(name)
        if not (d / ".git").is_dir():
            raise ProjectError(f"{name!r} is not a git project")
        return d

    def _is_dirty(self, project_dir: Path) -> bool:
        """Anything at all to commit. Used to decide whether a commit would be
        empty, where bookkeeping counts like everything else."""
        return bool(self._git(project_dir, "status", "--porcelain").strip())

    def _has_design_changes(self, project_dir: Path) -> bool:
        """Uncommitted changes to files a person would mind losing."""
        # -uall, or git collapses an untracked directory to a single ".blpl/"
        # entry and the prefix test below never sees the files inside it — which
        # is the exact case this exists to ignore.
        for line in self._git(project_dir, "status", "--porcelain", "-uall").splitlines():
            # Porcelain v1: two status characters, a space, then the path. A
            # rename is "old -> new"; the destination is what matters.
            path = line[3:].split(" -> ")[-1].strip().strip('"')
            if path and not path.startswith(_BOOKKEEPING):
                return True
        return False

    def _git(self, cwd: Path, *args: str, env: dict[str, str] | None = None) -> str:
        # `env` is extra environment for this one invocation — a leased
        # credential, never a stored one. Merged over the process environment
        # rather than replacing it, because git needs PATH and HOME too.
        proc = subprocess.run(
            ["git", *args],
            cwd=str(cwd),
            capture_output=True,
            text=True,
            check=False,
            timeout=300,
            env={**os.environ, **env} if env else None,
        )
        if proc.returncode != 0:
            raise ProjectError(
                f"git {' '.join(args)} failed ({proc.returncode}): {proc.stderr.strip()}"
            )
        return proc.stdout

    def _git_allow_fail(self, cwd: Path, *args: str) -> str:
        """For queries where a non-zero exit is a legitimate 'no answer' — e.g.
        counting against an upstream that isn't configured yet."""
        proc = subprocess.run(
            ["git", *args], cwd=str(cwd), capture_output=True, text=True, check=False, timeout=60
        )
        return proc.stdout.strip() if proc.returncode == 0 else ""

    def _git_capture(self, cwd: Path, *args: str) -> str:
        """Return stdout regardless of exit code. `git diff --no-index` exits 1
        whenever there IS a difference, which for us is the normal case, so a
        non-zero exit here is not an error."""
        proc = subprocess.run(
            ["git", *args], cwd=str(cwd), capture_output=True, text=True, check=False, timeout=120
        )
        return proc.stdout


def _porcelain_status(xy: str) -> str:
    """Map a two-char `git status --porcelain` code to a human word."""
    if xy == "??":
        return "untracked"
    code = xy.strip()
    if "D" in code:
        return "deleted"
    if "A" in code:
        return "added"
    if "R" in code:
        return "renamed"
    return "modified"
