"""Stage 7: validation.

Runs three families of checks and writes a consolidated validation_report.json:

  1. KLC checks on any symbols auto-generated by Stage 3 (via kicad-library-utils).
  2. DRC on the Stage 6 .kicad_pcb via `kicad-cli pcb drc` (JSON output).
  3. Coverage summary carried over from stage2.

Tool availability is probed at runtime; missing tools produce `skipped` results,
not failures — a missing `kicad-cli` shouldn't break a CI that only wants KLC.

Assumed kicad-cli: v9 or v10. The flags used here (`--format json`,
`--exit-code-violations`, `--severity-all`, `--output`) are common to both.
If you see a flag mismatch, bump the version branching below.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

from . import schema


# Three levels up: blpl/core/stage7_validate.py -> blpl/ -> board-layer-pipe-line/.
# This was parent.parent, so it looked for blpl/kicad-library-utils, which does
# not exist — meaning the KLC check has been reporting "skipped, tool not found"
# on every run since it was written, while the overall report still said ok.
_REPO_ROOT = Path(__file__).resolve().parents[2]
_CHECK_SYMBOL_PY = _REPO_ROOT / "kicad-library-utils" / "klc-check" / "check_symbol.py"


def _find_kicad_cli() -> str | None:
    for candidate in [
        shutil.which("kicad-cli"),
        "/Applications/KiCad/KiCad.app/Contents/MacOS/kicad-cli",
        "/usr/bin/kicad-cli",
    ]:
        if candidate and Path(candidate).exists():
            return candidate
    return None


def _kicad_cli_major(kicad_cli: str) -> int | None:
    """Return the KiCad major version (e.g., 9 or 10), or None if unparseable."""
    try:
        out = subprocess.run(
            [kicad_cli, "--version"], capture_output=True, text=True, check=False, timeout=10
        )
    except (OSError, subprocess.SubprocessError):
        return None
    text = (out.stdout or "") + (out.stderr or "")
    m = re.search(r"(\d+)\.(\d+)", text)
    return int(m.group(1)) if m else None


def _run_klc_symbol_checks(sym_files: list[Path]) -> dict:
    """Run kicad-library-utils/klc-check/check_symbol.py on each symbol file.

    The script exits non-zero if any KLC rule violations are found. We parse the
    per-file exit code and collect stderr/stdout verbatim for diagnostics.
    """
    if not _CHECK_SYMBOL_PY.exists():
        return {
            "ok": True,
            "skipped": True,
            "reason": f"klc-check not found at {_CHECK_SYMBOL_PY}",
            "results": [],
        }
    if not sym_files:
        return {"ok": True, "skipped": False, "results": [], "note": "no symbols to check"}

    results: list[dict] = []
    overall_ok = True
    for f in sym_files:
        proc = subprocess.run(
            [sys.executable, str(_CHECK_SYMBOL_PY), str(f), "-s"],
            capture_output=True,
            text=True,
            check=False,
            timeout=60,
        )
        ok = proc.returncode == 0
        overall_ok = overall_ok and ok
        # Keep a tail of output in the report so you can see why it failed.
        results.append(
            {
                "file": str(f),
                "ok": ok,
                "exit_code": proc.returncode,
                "stdout_tail": proc.stdout[-2000:] if proc.stdout else "",
                "stderr_tail": proc.stderr[-2000:] if proc.stderr else "",
            }
        )
    return {"ok": overall_ok, "skipped": False, "results": results}


def _run_drc(pcb_path: Path, output_json: Path) -> dict:
    """Run `kicad-cli pcb drc` on the PCB. Returns a result dict."""
    cli = _find_kicad_cli()
    if cli is None:
        return {
            "ok": True,
            "skipped": True,
            "reason": "kicad-cli not found in PATH or standard macOS location",
        }
    major = _kicad_cli_major(cli)
    if major is None:
        return {"ok": True, "skipped": True, "reason": "could not parse kicad-cli version"}

    output_json.parent.mkdir(parents=True, exist_ok=True)
    # Clear any previous run's report first. Everything below decides what
    # happened by asking whether this file exists, and kicad-cli writes nothing
    # when it cannot load the design at all — so a stale report was read as this
    # run's result and the *old* violation count was reported as current. That
    # turned a schematic kicad-cli refused to open ("Failed to load schematic",
    # exit 3) into a run whose numbers looked merely unchanged, which is the
    # worst way for an emitter bug to present.
    output_json.unlink(missing_ok=True)
    cmd = [
        cli,
        "pcb",
        "drc",
        "--format",
        "json",
        "--severity-all",
        "--exit-code-violations",
        "--output",
        str(output_json),
        str(pcb_path),
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True, check=False, timeout=120)
    result: dict = {
        "ok": proc.returncode == 0,
        "skipped": False,
        "kicad_cli_major": major,
        "exit_code": proc.returncode,
        "report_json": str(output_json) if output_json.exists() else None,
        "stdout_tail": proc.stdout[-2000:] if proc.stdout else "",
        "stderr_tail": proc.stderr[-2000:] if proc.stderr else "",
    }
    if output_json.exists():
        try:
            data = json.loads(output_json.read_text())
            result["violation_count"] = len(data.get("violations", []))
            result["unconnected_count"] = len(data.get("unconnected_items", []))
            result["schematic_parity_count"] = len(data.get("schematic_parity", []))
        except json.JSONDecodeError:
            pass
    return result


def _run_erc(sch_path: Path, output_json: Path) -> dict:
    """Run `kicad-cli sch erc` on the schematic. Same shape of result as _run_drc."""
    cli = _find_kicad_cli()
    if cli is None:
        return {"ok": True, "skipped": True, "reason": "kicad-cli not found"}
    major = _kicad_cli_major(cli)
    if major is None:
        return {"ok": True, "skipped": True, "reason": "could not parse kicad-cli version"}

    output_json.parent.mkdir(parents=True, exist_ok=True)
    # Clear any previous run's report first. Everything below decides what
    # happened by asking whether this file exists, and kicad-cli writes nothing
    # when it cannot load the design at all — so a stale report was read as this
    # run's result and the *old* violation count was reported as current. That
    # turned a schematic kicad-cli refused to open ("Failed to load schematic",
    # exit 3) into a run whose numbers looked merely unchanged, which is the
    # worst way for an emitter bug to present.
    output_json.unlink(missing_ok=True)
    cmd = [
        cli,
        "sch",
        "erc",
        "--format",
        "json",
        "--severity-all",
        "--exit-code-violations",
        "--output",
        str(output_json),
        str(sch_path),
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True, check=False, timeout=120)
    result: dict = {
        "ok": proc.returncode == 0,
        "skipped": False,
        "kicad_cli_major": major,
        "exit_code": proc.returncode,
        "report_json": str(output_json) if output_json.exists() else None,
        "stdout_tail": proc.stdout[-2000:] if proc.stdout else "",
        "stderr_tail": proc.stderr[-2000:] if proc.stderr else "",
    }
    if output_json.exists():
        try:
            data = json.loads(output_json.read_text())
            result["violation_count"] = len(data.get("violations", []))
        except json.JSONDecodeError:
            pass
    return result


def _coverage_summary(coverage_path: Path) -> dict:
    if not coverage_path.exists():
        return {"ok": True, "skipped": True, "reason": "no coverage_report.json"}
    data = schema.load_json(coverage_path)
    s = data.get("summary", {})
    return {
        "ok": s.get("miss", 0) == 0,
        "skipped": False,
        "total": s.get("total", 0),
        "hit": s.get("hit", 0),
        "needs_variant": s.get("needs_variant", 0),
        "miss": s.get("miss", 0),
    }


def run(
    project_dir: Path,
    *,
    pcb_path: Path | None = None,
    sch_path: Path | None = None,
    generated_symbols_dir: Path | None = None,
    coverage_path: Path | None = None,
    board: str | None = None,
) -> dict:
    """Run all Stage 7 checks and write validation_report.json into .pipeline/.

    ``board`` qualifies every file this stage reads or writes, the way the
    rest of the pipeline does (``validation_report.sensor.json``). Without it
    a multi-board project's boards overwrote one report and read one
    another's coverage.
    """
    from .project_manifest import artifact_path

    project_dir = Path(project_dir)
    pipeline_dir = project_dir / ".pipeline"
    pipeline_dir.mkdir(parents=True, exist_ok=True)

    def _p(name: str) -> Path:
        return artifact_path(project_dir, name, board=board)

    gen_symbols = generated_symbols_dir or (project_dir / "generated" / "symbols")
    cov = coverage_path or _p("coverage_report")

    sym_files = sorted(gen_symbols.glob("*.kicad_sym")) if gen_symbols.exists() else []
    klc_result = _run_klc_symbol_checks(sym_files)

    erc_result: dict
    if sch_path is not None and sch_path.exists():
        erc_result = _run_erc(sch_path, _p("erc_report"))
    else:
        erc_result = {"ok": True, "skipped": True, "reason": "no .kicad_sch supplied"}

    drc_result: dict
    if pcb_path is not None and pcb_path.exists():
        drc_result = _run_drc(pcb_path, _p("drc_report"))
    else:
        drc_result = {"ok": True, "skipped": True, "reason": "no .kicad_pcb supplied"}

    cov_result = _coverage_summary(cov)

    overall_ok = klc_result["ok"] and erc_result["ok"] and drc_result["ok"] and cov_result["ok"]
    report = {
        "ok": overall_ok,
        "klc_symbols": klc_result,
        "erc": erc_result,
        "drc": drc_result,
        "coverage": cov_result,
    }
    _p("validation_report").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    return report
